# Generated by Django 2.1.3 on 2019-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190612_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_type',
            field=models.IntegerField(choices=[(0, 'alias'), (1, 'absolutely_url')], default=1),
            preserve_default=False,
        ),
    ]
