# Generated by Django 2.1.3 on 2019-06-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_menu_url_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='身份证号'),
        ),
    ]
