# Generated by Django 2.1.3 on 2019-06-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190621_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='合同名称')),
                ('template', models.TextField(verbose_name='合同内容')),
            ],
            options={
                'verbose_name': '合同范本',
                'verbose_name_plural': '合同范本',
            },
        ),
        migrations.AddField(
            model_name='classlist',
            name='contract',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm.ContractTemplate', verbose_name='合同'),
            preserve_default=False,
        ),
    ]
