# Generated by Django 2.1.3 on 2019-07-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_menu_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stu_account',
            field=models.ForeignKey(blank=True, help_text='学员报名后方可才能创建账户', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='关联学员账号'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order_by',
            field=models.SmallIntegerField(choices=[(0, '首页'), (1, '数据关系'), (2, '上课管理'), (3, '缴费管理'), (4, '系统管理')], null=True, verbose_name='排序'),
        ),
    ]
