# Generated by Django 2.1.3 on 2019-07-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20190702_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('table_obj_delete', '删除表单中相应条目'),)},
        ),
    ]
