# Generated by Django 2.1.3 on 2019-07-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190708_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('table_obj_change', '查看客户库表单权限'),)},
        ),
    ]
